"""Prompt assembly for the Phase 3A Aggregation component."""

from __future__ import annotations

import json
from typing import Any


def _json_block(payload: Any) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=True)


def _render_contradiction_block(source_contradictions: list[dict[str, Any]]) -> str:
    if not source_contradictions:
        return "SOURCE_CONTRADICTIONS: []"
    lines = ["SOURCE_CONTRADICTIONS:"]
    for c in source_contradictions:
        lines.append(f'  id={c["id"]}  text="{c["text"]}"')
    return "\n".join(lines)


def _render_output_contract() -> str:
    return """
{
  "aggregation_handoff": {
    "batch_id": string,
    "round_id": string,
    "hypothesis_id": string,
    "merged_findings": [string],
    "evidence_refs": [string],
    "preserved_contradiction_ids": [string],
    "open_gaps": [string],
    "update_focus": string
  }
}
"""


def build_aggregation_prompt(
    *,
    batch_id: str,
    round_id: str,
    hypothesis_id: str,
    normalized_inputs: dict[str, Any],
) -> str:
    source_contradictions = normalized_inputs.get("source_contradictions", [])
    sections = [
        "ROLE:",
        "You are Aggregation. Stay inside one hypothesis-local, round-local merge after Worker and before State Manager.",
        "",
        "=== CRITICAL OUTPUT COMPLIANCE REQUIREMENT ===",
        "",
        "THE OUTPUT CONTRACT IS THE HIGHEST PRIORITY REQUIREMENT IN THIS PROMPT.",
        "",
        "BEFORE RETURNING ANY RESPONSE:",
        "",
        "1. VERIFY THAT THE RESPONSE EXACTLY MATCHES THE REQUIRED OUTPUT SCHEMA.",
        "2. VERIFY THAT NO REQUIRED FIELD IS MISSING.",
        "3. VERIFY THAT NO EXTRA FIELD IS PRESENT.",
        "4. VERIFY THAT ALL ENUM VALUES ARE VALID.",
        "5. VERIFY THAT ALL REQUIRED LISTS ARE PRESENT AND CORRECTLY TYPED.",
        "6. IF ANY PART OF THE RESPONSE WOULD VIOLATE THE OUTPUT CONTRACT, REVISE THE RESPONSE BEFORE RETURNING IT.",
        "",
        "OUTPUT CONTRACT COMPLIANCE TAKES PRIORITY OVER REASONING COMPLETENESS.",
        "",
        "DO NOT RETURN AN APPROXIMATE RESPONSE.",
        "DO NOT RETURN A PARTIALLY VALID RESPONSE.",
        "DO NOT RETURN ADDITIONAL EXPLANATIONS.",
        "DO NOT RETURN MARKDOWN.",
        "DO NOT RETURN CODE FENCES.",
        "",
        "DO NOT INFER PERMITTED OUTPUTS.",
        "DO NOT GENERALIZE THE SCHEMA.",
        "ONLY EMIT FIELDS AND VALUES EXPLICITLY ALLOWED.",
        "",
        "FINAL CHECK:",
        "",
        "IMMEDIATELY BEFORE PRODUCING THE RESPONSE,",
        "PERFORM A SELF-CHECK AGAINST THE OUTPUT RULES.",
        "",
        "IF THE RESPONSE DOES NOT SATISFY EVERY OUTPUT RULE,",
        "REWRITE IT BEFORE RETURNING IT.",
        "",
        "OUTPUT VALIDITY IS MORE IMPORTANT THAN ANALYSIS QUALITY.",
        "",
        "RETURN ONLY A FULLY VALID OUTPUT OBJECT.",
        "",
        "Do not reroute, replan, mutate canonical state, emit critic feedback, or summarize raw traces.",
        "Preserve grounded contradictions and unresolved gaps instead of flattening them away.",
        "",
        "=== AGGREGATION OBJECTIVE ===",

        "Aggregation has two responsibilities:",

        "1. Preserve evidence generated by worker tasks.",
        "2. Extract hypothesis-level conclusions that emerge only when multiple worker investigations are considered together.",
        "",
        "Preserve evidence first.",
        "Then reason over evidence.",
        "",
        "Do not replace evidence with interpretation.",
        "Add interpretation on top of evidence.",
        "",
        "TASK:",
        _json_block(
            {
                "batch_id": batch_id,
                "round_id": round_id,
                "hypothesis_id": hypothesis_id,
                "worker_result_count": normalized_inputs.get("worker_result_count", 0),
                "expected_task_ids": normalized_inputs.get("expected_task_ids", []),
                "selected_task_ids": normalized_inputs.get("selected_task_ids", []),
            }
        ),
        "",
        "=== HYPOTHESIS CONTEXT ===",
        "",
        "Aggregation should evaluate worker evidence against the",
        "original hypothesis intent.",
        "",
        "Strategic objective defines what the hypothesis was",
        "attempting to determine.",
        "",
        "Key checks define the major questions that were investigated.",
        "",
        "Success criteria define what evidence would support or",
        "weaken the hypothesis.",
        "",
        _json_block(
            {
                "strategic_objective":
                    normalized_inputs.get("strategic_objective", ""),
                "key_checks":
                    normalized_inputs.get("key_checks", []),
                "success_criteria":
                    normalized_inputs.get("success_criteria", []),
            }
        ),
        "",
        "=== TASK INTENT CONTEXT ===",
        "",
        "Aggregation should evaluate evidence relative to the",
        "investigation objective of each task.",
        "",
        "For each task consider:",
        "",
        "* what the task attempted to determine",
        "* what evidence was collected",
        "* whether the task objective appears resolved",
        "* whether the evidence supports, weakens, or leaves",
        "  unresolved the investigated question",
        "",
        "If task metadata exists inside normalized_inputs,",
        "render it.",
        "",
        "TASK_CONTEXT:",
        _json_block(normalized_inputs.get("task_context", [])),
        "",
        "SOURCE_WORKER_RESULTS:",
        _json_block(normalized_inputs.get("worker_results", [])),
        "",
        "=== TASK-AWARE SYNTHESIS ===",
        "",
        "Each worker task was created to investigate a different aspect",
        "of the same hypothesis.",
        "",
        "For each task:",

        "- identify what it attempted to determine",
        "- identify what evidence it produced",
        "- identify whether its investigation objective appears resolved",

        "Then evaluate the hypothesis as a whole.",

        "Do not treat worker findings as independent lists.",
        "Treat them as evidence produced by coordinated investigations.",
        "",
        "OVERLAP_DIAGNOSTICS:",
        _json_block(normalized_inputs.get("overlap_diagnostics", [])),
        "",
        "=== CONVERGENCE ANALYSIS ===",

        "When multiple worker tasks independently support",
        "the same observation:",

        "- preserve the original findings",
        "- recognize the convergence explicitly",
        "- treat repeated confirmation as stronger evidence",

        "Repeated evidence should increase confidence,",
        "not merely increase finding count.",
        "",
        "Aggregation may generate additional merged findings",
        "that describe evidence convergence.",
        "",
        "=== TRACEABILITY PRESERVATION ===",
        "",
        "Worker findings are primary evidence.",
        "",
        "Do not remove worker findings merely because",
        "multiple tasks reported similar observations.",
        "",
        "Preserve traceability.",
        "",
        "Convergence findings should be added in addition",
        "to worker findings, not replace them.",
        "",
        "Preserve evidence lineage whenever possible.",
        "",
        "Evidence preservation has priority over compression.",
        "",
        "=== HYPOTHESIS-LEVEL EVALUATION ===",
        "",
        "Evaluate the hypothesis as a whole.",
        "",
        "Determine:",
        "",
        "* which observations gained strongest support",
        "* which explanations weakened",
        "* which explanations remain unresolved",
        "* whether the hypothesis objective appears supported,",
        "  weakened, unresolved, or contradicted",
        "",
        "These conclusions may be added as merged findings.",
        "",
        "Such conclusions should emerge from multiple worker",
        "investigations rather than a single worker result.",
        "",
        "Do not discard supporting evidence when producing",
        "hypothesis-level conclusions.",
        "",
        "=== GAP PRIORITIZATION ===",
        "",
        "Open gaps should represent uncertainty that materially affects",
        "the hypothesis outcome.",
        "",
        "Do not copy all worker limitations.",
        "",
        "Open gaps should correspond to uncertainties that",
        "would materially change confidence in the hypothesis.",
        "",
        "Prefer a small number of high-value gaps over",
        "large collections of low-impact limitations.",
        "",
        "Do not automatically copy every worker limitation",
        "into open_gaps.",
        "",
        "Prioritize gaps that:",
        "",
        "- block shortcut verification",
        "- block contradiction resolution",
        "- block causal interpretation",
        "- block confidence in the hypothesis",
        "",
        "Avoid low-impact implementation limitations.",
        "",
        "=== SHORTCUT EVIDENCE ESCALATION ===",

        "When multiple worker tasks report:",

        "- low_entropy",
        "- dominant_value",
        "- high_class_separation",
        "- shortcut-like behavior",
        "- predictive leverage",
        "- representation-sensitive predictors",

        "treat this as high-value evidence.",

        "Preserve these observations explicitly.",

        "Do not dilute repeated shortcut signals into",
        "generic findings.",
        _render_contradiction_block(source_contradictions),
        "",
        "OUTPUT CONTRACT (typed JSON tree — this is the authoritative schema):",
        _render_output_contract(),
        "",
        "=== FIELD RULES ===",
        "Only cite evidence_refs that appear in SOURCE_WORKER_RESULTS.",
        'For preserved_contradiction_ids: output ID STRINGS ONLY, never contradiction text.',
        'IDs must come from SOURCE_CONTRADICTIONS shown above.',
        'Do not invent, summarize, paraphrase, merge, or synthesize contradiction text.',
        'Do not include a "preserved_contradictions" field in your output — only preserved_contradiction_ids.',
        "Keep update_focus state-facing and grounded, but do not describe state mutation.",
        "",
        "=== EXAMPLES ===",
        'GOOD (ID only):  "preserved_contradiction_ids": ["contr_0", "contr_3"]',
        'BAD (no text):  "preserved_contradictions": ["some text here"]',
        'BAD (no text):  "preserved_contradiction_ids": ["Unknown ref that is not in SOURCE_CONTRADICTIONS"]',
        "=== UPDATE FOCUS GUIDANCE ===",

        "update_focus should identify the single most valuable",
        "next investigation direction.",

        "Prioritize:",

        "1. contradiction resolution",
        "2. shortcut verification",
        "3. major unresolved uncertainty",
        "4. secondary characterization",

        "Prefer one high-value focus over a long list",
        "of future directions.",
        "",
        "update_focus should be driven by the highest-value",
        "remaining uncertainty identified through the",
        "hypothesis-level evaluation.",
        "",
        "Do not simply concatenate worker recommendations.",
        "",
        "Prefer the single investigation direction that",
        "would most improve confidence in the hypothesis.",
    ]

    return "\n".join(sections).strip() + "\n"