"""Prompt assembly for the Phase 3B Partition Memory Extractor."""

from __future__ import annotations

import json
from typing import Any

from partition_memory_extractor.contracts import (
    ARTIFACT_FAMILIES,
    PROMPT_VERSION,
)


def _json_block(payload: Any) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=True, default=str)


def _render_output_contract() -> str:
    return """{
  "partition_id": string,
  "recommendation": string,
  "overall_assessment": {
    "risk_level": string,
    "confidence_level": string
  },
  "artifact_families": [
    {
      "family": string,
      "impact": number,
      "support": string,
      "evidence": [string]
    }
  ],
  "major_findings": [
    {
      "canonical_name": string,
      "display_name": string,
      "impact": number,
      "confidence": number,
      "artifact_families": [string]
    }
  ],
  "open_risks": [any],
  "coverage_signals": [any]
}"""


def build_partition_memory_prompt(
    *,
    partition_id: str,
    report_markdown: str,
    component_run: dict[str, Any],
    runtime_metrics: dict[str, Any],
) -> str:
    """Build the complete partition memory extraction prompt.

    Args:
        partition_id: Human-readable partition identifier.
        report_markdown: The markdown report generated by final_batch_report.
        component_run: Metadata from the final_batch_report component_run.json.
        runtime_metrics: Metrics from the final_batch_report runtime_metrics.json.

    Returns:
        Complete prompt string ready for LLM consumption.
    """
    sections: list[str] = []

    # Section 1: CRITICAL OUTPUT COMPLIANCE REQUIREMENT
    sections.append(
        "=== CRITICAL OUTPUT COMPLIANCE REQUIREMENT ===\n"
        "\n"
        "THE OUTPUT CONTRACT IS THE HIGHEST PRIORITY REQUIREMENT IN THIS PROMPT.\n"
        "\n"
        "BEFORE RETURNING ANY RESPONSE:\n"
        "\n"
        "1. VERIFY THAT THE RESPONSE EXACTLY MATCHES THE REQUIRED OUTPUT SCHEMA.\n"
        "2. VERIFY THAT NO REQUIRED FIELD IS MISSING.\n"
        "3. VERIFY THAT NO EXTRA FIELD IS PRESENT.\n"
        "4. VERIFY THAT ALL ENUM VALUES ARE VALID.\n"
        "5. VERIFY THAT ALL REQUIRED LISTS ARE PRESENT AND CORRECTLY TYPED.\n"
        "6. IF ANY PART OF THE RESPONSE WOULD VIOLATE THE OUTPUT CONTRACT, REVISE THE RESPONSE BEFORE RETURNING IT.\n"
        "\n"
        "OUTPUT CONTRACT COMPLIANCE TAKES PRIORITY OVER REASONING COMPLETENESS.\n"
        "\n"
        "DO NOT RETURN AN APPROXIMATE RESPONSE.\n"
        "DO NOT RETURN A PARTIALLY VALID RESPONSE.\n"
        "DO NOT RETURN ADDITIONAL EXPLANATIONS.\n"
        "DO NOT RETURN MARKDOWN.\n"
        "DO NOT RETURN CODE FENCES.\n"
        "\n"
        "DO NOT INFER PERMITTED OUTPUTS.\n"
        "DO NOT GENERALIZE THE SCHEMA.\n"
        "ONLY EMIT FIELDS AND VALUES EXPLICITLY ALLOWED.\n"
        "\n"
        "FINAL CHECK:\n"
        "\n"
        "IMMEDIATELY BEFORE PRODUCING THE RESPONSE,\n"
        "PERFORM A SELF-CHECK AGAINST THE OUTPUT RULES.\n"
        "\n"
        "IF THE RESPONSE DOES NOT SATISFY EVERY OUTPUT RULE,\n"
        "REWRITE IT BEFORE RETURNING IT.\n"
        "\n"
        "OUTPUT VALIDITY IS MORE IMPORTANT THAN ANALYSIS QUALITY.\n"
        "\n"
        "RETURN ONLY A FULLY VALID OUTPUT OBJECT.\n"
        "\n"
        "=== ROLE ===\n"
        "You are the Partition Memory Extractor.\n"
        "\n"
        "Your role is to convert a large Final Batch Report into a compact,\n"
        "normalized semantic representation suitable for dataset-level synthesis.\n"
        "\n"
        "This is not a summarization task.\n"
        "\n"
        "This is a semantic compression and categorization task.\n"
        "\n"
        "Your objectives are:\n"
        "1. Normalize findings into canonical representations.\n"
        "2. Assign each major finding to one or more artifact families.\n"
        "3. Preserve impact and confidence assessments.\n"
        "4. Preserve the auditor recommendation.\n"
        "5. Extract reusable dataset-level signals.\n"
        "\n"
        "=== INPUT BOUNDARIES ===\n"
        "You receive the full report markdown and execution metadata.\n"
        "Do not add new findings or assessments not present in the report.\n"
        "Do not remove or weaken critical findings present in the report.\n"
        "Preserve the original recommendation from the auditor.\n"
        "\n"
        "=== ARTIFACT FAMILY CATALOG ===\n"
        "Every major finding MUST be mapped to at least one artifact family.\n"
        "Multiple families per finding are allowed.\n"
        "\n"
        "Available artifact families:\n"
    )

    families_text = "\n".join(f"- {f}" for f in ARTIFACT_FAMILIES)
    sections.append(families_text)

    sections.append(
        "\n"
        "=== OUTPUT CONTRACT ===\n"
        f"{_render_output_contract()}\n"
        "\n"
        "=== FIELD RULES ===\n"
        "partition_id: Must match the partition_id provided in the input.\n"
        "recommendation: Must reflect the auditor's recommendation from the report.\n"
        "overall_assessment.risk_level: String summary of overall risk.\n"
        "overall_assessment.confidence_level: String summary of overall confidence.\n"
        "artifact_families: One entry per artifact family present in this partition.\n"
        "  Each entry must contain: family (string), impact (number),\n"
        "  support (string describing evidence strength), evidence (list of canonical finding names).\n"
        "major_findings: Normalized representation of each important finding.\n"
        "  Each entry must contain: canonical_name (string identifier),\n"
        "  display_name (human-readable name), impact (number),\n"
        "  confidence (number), artifact_families (list of family strings).\n"
        "  At least one artifact_family per finding.\n"
        "open_risks: Additional risks or open items from the report.\n"
        "coverage_signals: Dataset-level coverage signals extracted from the report.\n"
        "\n"
        "=== INPUT METADATA ===\n"
        f"Partition ID: {partition_id}\n"
        f"Report Investigation Count: {runtime_metrics.get('investigated_findings_count', 'unknown')}\n"
        f"Report Additional Findings Count: {runtime_metrics.get('additional_findings_count', 'unknown')}\n"
        f"Report Status: {component_run.get('status', 'unknown')}\n"
        "\n"
        "=== FINAL BATCH REPORT ===\n"
        "Below is the complete Final Batch Report for this partition.\n"
        "Extract, normalize, and categorize the findings into the output contract.\n"
        "\n"
        f"{report_markdown}"
    )

    return "\n\n".join(sections).strip() + "\n"