"""Prompt assembly for Phase 3A Semantic Extraction."""

from __future__ import annotations

import json
from typing import Any

from semantic_extraction.contracts import (
    VALID_LOCALITY_SCOPE_TYPES,
    VALID_REGION_KINDS,
    VALID_REGION_STATUSES,
)


def _render_json_block(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=True)


def _render_canonical_schema_examples(batch_id: str) -> str:
    return "\n".join(
        [
            "=== CANONICAL JSON SHAPES ===",
            "Use these exact nested shapes. Do not flatten them, rename keys, or change types.",
            "",
            "feature_scope (required inside every compressed region; strongly recommended for weak signals too):",
            "{",
            '  "features": ["feature_a", "feature_b"],',
            '  "feature_groups": ["feature_group_name"],',
            '  "locality": {',
            '    "scope_type": "dependency_cluster",',
            '    "scope_value": "feature_a|feature_b",',
            '    "localized": true,',
            '    "notes": ["short grounded note"]',
            "  }",
            "}",
            "",
            "If there are no concrete feature names available in the overview evidence, set features to a non-empty list such as [\"__dataset__\"] or the top feature from projected_evidence.feature_scope_refs. Do NOT leave features empty.",
            "feature_scope for a partition-wide region can use:",
            "{",
            '  "features": ["feature_a"],',
            '  "feature_groups": [],',
            '  "locality": {',
            '    "scope_type": "partition_global",',
            f'    "scope_value": "{batch_id}",',
            '    "localized": false,',
            '    "notes": ["partition-level observation"]',
            "  }",
            "}",
            "",
            "uncertainty_notes must always be a JSON list of strings, for example: [\"note 1\", \"note 2\"].",
            "Never emit a string, object, or null for uncertainty_notes.",
            "",
            "compressed region skeleton:",
            "{",
            '  "region_id": "region_1_example",',
            '  "region_kind": "dependency_region",',
            '  "status": "active",',
            '  "summary": "grounded summary",',
            '  "structural_descriptors": ["descriptor 1"],',
            '  "feature_scope": {',
            '    "features": ["feature_a", "feature_b"],',
            '    "feature_groups": ["feature_group_name"],',
            '    "locality": {',
            '      "scope_type": "dependency_cluster",',
            '      "scope_value": "feature_a|feature_b",',
            '      "localized": true,',
            '      "notes": []',
            "    }",
            "  }",
            '  "evidence_refs": ["e1"],',
            '  "supporting_patterns": ["pattern 1"],',
            '  "contextual_modifiers": ["modifier 1"],',
            '  "uncertainty_notes": ["note 1"],',
            '  "contradiction_refs": [],',
            '  "tension_refs": []',
            "}",
            "",
            "weak signal skeleton:",
            "{",
            '  "weak_signal_id": "weak_1_example",',
            '  "descriptor": "grounded descriptor",',
            '  "feature_scope": {',
            '    "features": ["feature_a"],',
            '    "feature_groups": [],',
            '    "locality": {',
            '      "scope_type": "feature_group",',
            '      "scope_value": "feature_a",',
            '      "localized": true,',
            '      "notes": []',
            "    }",
            "  }",
            '  "evidence_refs": ["e1"],',
            '  "preservation_reason": "grounded reason",',
            '  "contextual_modifiers": [],',
            '  "uncertainty_notes": []',
            "}",
            "",
            "For contradictions and tensions, follow the same list/object discipline: every refs field is a list, every notes field is a list, and every feature_scope uses the nested object shape above.",
        ]
    )


def build_semantic_extraction_prompt(
    *,
    batch_id: str,
    projected_evidence: dict[str, Any],
    normalized_partition_context: dict[str, list[str]],
) -> str:
    region_kinds = ", ".join(sorted(VALID_REGION_KINDS))
    region_statuses = ", ".join(sorted(VALID_REGION_STATUSES))
    locality_scope_types = ", ".join(sorted(VALID_LOCALITY_SCOPE_TYPES))

    return "\n".join(
        [
            "=== CRITICAL OUTPUT COMPLIANCE REQUIREMENT ===",
            "",
            "THE OUTPUT CONTRACT IS THE HIGHEST PRIORITY REQUIREMENT IN THIS PROMPT.",
            "",
            "BEFORE RETURNING ANY RESPONSE:",
            "",
            "1. VERIFY THAT THE RESPONSE EXACTLY MATCHES THE REQUIRED OUTPUT SCHEMA.",
            "2. VERIFY THAT NO REQUIRED FIELD IS MISSING.",
            "3. VERIFY THAT NO EXTRA FIELD IS PRESENT.",
            "4. VERIFY THAT ALL ENUM VALUES ARE VALID.",
            "5. VERIFY THAT ALL REQUIRED LISTS ARE PRESENT AND CORRECTLY TYPED.",
            "6. IF ANY PART OF THE RESPONSE WOULD VIOLATE THE OUTPUT CONTRACT, REVISE THE RESPONSE BEFORE RETURNING IT.",
            "",
            "OUTPUT CONTRACT COMPLIANCE TAKES PRIORITY OVER REASONING COMPLETENESS.",
            "",
            "DO NOT RETURN AN APPROXIMATE RESPONSE.",
            "DO NOT RETURN A PARTIALLY VALID RESPONSE.",
            "DO NOT RETURN ADDITIONAL EXPLANATIONS.",
            "DO NOT RETURN MARKDOWN.",
            "DO NOT RETURN CODE FENCES.",
            "",
            "DO NOT INFER PERMITTED OUTPUTS.",
            "DO NOT GENERALIZE THE SCHEMA.",
            "ONLY EMIT FIELDS AND VALUES EXPLICITLY ALLOWED.",
            "",
            "FINAL CHECK:",
            "",
            "IMMEDIATELY BEFORE PRODUCING THE RESPONSE,",
            "PERFORM A SELF-CHECK AGAINST THE OUTPUT RULES.",
            "",
            "IF THE RESPONSE DOES NOT SATISFY EVERY OUTPUT RULE,",
            "REWRITE IT BEFORE RETURNING IT.",
            "",
            "OUTPUT VALIDITY IS MORE IMPORTANT THAN ANALYSIS QUALITY.",
            "",
            "RETURN ONLY A FULLY VALID OUTPUT OBJECT.",
            "",
            "=== ROLE ===",
            "You are the Phase 3A Semantic Extraction module.",
            "Your job is to compress grounded overview evidence into a broad structural substrate.",
            "You are part of a forensic dataset auditing system focused on identifying structural irregularities, representation-sensitive patterns, shortcut-like signals, unstable dependencies, and epistemically suspicious regularities inside telemetry datasets.",
            "Your role is not to optimize predictive performance or maximize classification accuracy.",
            "Your role is to preserve uncertainty, isolate bounded observable patterns, and support investigation of potentially misleading, unstable, shortcut-like, or structurally concentrated signals.",
            "",
            "=== OBJECTIVE ===",
            f"Initialize the structural substrate for batch_id={batch_id}.",
            "Preserve broad structural regions, weak but coherent signals, contradictions, and unresolved tensions.",
            "",
            "=== BOUNDARIES ===",
            "Use partition context only to temper interpretation, never to validate evidence.",
            "Do not generate hypotheses.",
            "Do not prioritize, rank, plan, route, or recommend next steps.",
            "Do not introduce causal explanations or artifact-family conclusions.",
            "=== SEMANTIC GOVERNANCE NOTES ===",
            "Prefer descriptive, probabilistic, and evidence-based phrasing in explanation fields (for example `uncertainty_notes` and `contextual_modifiers`).",
            "Action, causal, and validation wording such as 'artifact', 'cause', 'causal', 'validate', 'confirm', 'prove', 'hypothesis', 'plan', 'prioritiz(e|ation)', 'route', or 'worker' may trigger semantic governance flags in logs, but it does not invalidate the output.",
            "When practical, rewrite those phrases into descriptive or evidence-based formulations. Examples:",
            "- Instead of 'X causes Y' write 'X may be associated with Y' or 'evidence is consistent with an association between X and Y'.",
            "- Instead of 'we should validate' write 'this pattern is consistent with the evidence and may merit further validation' or 'evidence supports additional verification steps'.",
            "- Instead of 'artifact' write 'observable pattern' or 'signal consistent with a family of artifacts'.",
            "Keep `uncertainty_notes` descriptive, probabilistic, and grounded; causal or operational wording is observable telemetry rather than a blocking condition.",
            "Keep the output compact and grounded in the provided evidence IDs.",
            "",
            "=== OUTPUT RULES ===",
            "Return valid JSON only.",
            "Do not use markdown or code fences.",
            "Return exactly these top-level fields:",
            "substrate_id, batch_id, compressed_regions, preserved_weak_signals, contradictions, unresolved_tensions.",
            "Each compressed region must include:",
            "region_id, region_kind, status, summary, structural_descriptors, feature_scope, evidence_refs, supporting_patterns, contextual_modifiers, uncertainty_notes, contradiction_refs, tension_refs.",
            "Each weak signal must include:",
            "weak_signal_id, descriptor, feature_scope, evidence_refs, preservation_reason, contextual_modifiers, uncertainty_notes.",
            "Each contradiction must include:",
            "contradiction_id, contradiction_kind, description, feature_scope, supporting_evidence_refs, conflicting_evidence_refs, context_notes, downstream_relevance.",
            "Each tension must include:",
            "tension_id, description, related_region_ids, evidence_refs, context_notes, reason_unresolved.",
            f"Allowed region_kind values: {region_kinds}.",
            f"Allowed status values: {region_statuses}.",
            f"Allowed locality.scope_type values: {locality_scope_types}.",
            "Every compressed region feature_scope must include features, feature_groups, and locality.",
            "features MUST be a non-empty JSON list. If no concrete feature names are present in the overview evidence, choose one representative feature from projected_evidence.feature_scope_refs (prefer the top-ranked) or use the sentinel __dataset__ explicitly to indicate a pure partition-level observation. Never emit an empty list for features.",
            "Every locality must include scope_type, scope_value, localized, and notes.",
            "For weak signals, contradictions, and tensions, keep the same nested feature_scope shape and use list-valued refs/notes fields.",
            "Use [] for empty lists. Never emit null for any list field.",
            "All evidence_refs must cite only evidence_id values present in the overview evidence input.",
            "",
            _render_canonical_schema_examples(batch_id),
            "",
            "=== PARTITION CONTEXT ===",
            _render_json_block(normalized_partition_context),
            "",
            "=== PROJECTED OVERVIEW EVIDENCE ===",
            _render_json_block(projected_evidence),
        ]
    )